### ISSUE TITLE
build with v3.3

### ISSUE THREAD

**Issue by kuzmanzs** [karawin/Ka-Radio32#189]
Hi,

I try master branch compile with v3.3 but I get following error
`/home/me/dev/projects/Ka-Radio32/main/app_main.c:627:22: error: invalid initializer
   ip_addr_t ipdns0 = dns_getserver(0);
                      ^
/home/zsolt/dev/projects/c/esp/esp32/esp-idf-past/v3.3/esp-idf/make/component_wrapper.mk:289: recipe for target 'app_main.o' failed
make[1]: *** [app_main.o] Error 1
/home/zsolt/dev/projects/c/esp/esp32/esp-idf-past/v3.3/esp-idf/make/project.mk:552: recipe for target 'component-main-build' failed
make: *** [component-main-build] Error 2
`

Environment on Linux:
esp-idf v3.3
xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-96-g2852398) 5.2.0

Whitch IDF version is working with master now ?

**Comment by karawin** [comment]
see https://github.com/karawin/Ka-Radio32/issues/172 
Same problem?
